### ISSUE TITLE
error in initialize()

### ISSUE THREAD

**Issue by yousofkakhki** [stefanhaustein/quake2-libgdx-port#1]
hi
Error:(14, 14) error: constructor GdxQuake2 in class GdxQuake2 cannot be applied to given types;
required: PlatformTools
found: no arguments
reason: actual and formal argument lists differ in length
 i get this error, what shoul i pass to constructor
tnx in advance

**Comment by stefanhaustein** [comment]
I am still working on making the desktop version run with libgdx, will look into the other afterwards. Hope to get the desktop version working this weekend, don't have an eta for the others yet.

**Comment by stefanhaustein** [comment]
p.s. The constructor needs the corresponding platform instance of PlatformTools (but I have only ported DesktopTools so far)

**Comment by stefanhaustein** [comment]
Should be working now for Desktop and GWT (with lots of debug logging though).
Android's unzip has problems with the zip exe file, might work if you re-pack
